### ISSUE TITLE
Block embed is not in the cheat sheet

### ISSUE THREAD

**Issue by orphee-celui-qui-ne-sait-rien** [ddauber/athens-cheat-sheet#1]
![Capture d’écran, le 2021-03-15 à 10 03 11 AM](https://user-images.githubusercontent.com/79347623/111183590-ae7c9480-8575-11eb-8b69-abda9589c1e6.png)

Info about the block embed is missing
![Capture d’écran, le 2021-03-15 à 10 01 59 AM](https://user-images.githubusercontent.com/79347623/111183493-9278f300-8575-11eb-8f21-8e7df3793f44.png)
![Capture d’écran, le 2021-03-15 à 10 02 04 AM](https://user-images.githubusercontent.com/79347623/111183498-93118980-8575-11eb-8467-2f3743a6a157.png)

**Comment by ddauber** [comment]
Thanks, @orphee-celui-qui-ne-sait-rien!

Well spotted. I updated the cheat sheet to include block-embeds.
